export const AUTH_START = 'SPK/AUTH_START';
export const AUTH_SUCCESS = 'SPK/AUTH_SUCCESS';
export const AUTH_FAIL = 'SPK/AUTH_FAIL';
export const AUTH_LOGOUT = 'SPK/AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SPK/SET_AUTH_REDIRECT_PATH';

export const SHIPPINGADV_EXP_INSERT_START = 'SPK/SHIPPINGADV_EXP_INSERT_START';
export const SHIPPINGADV_EXP_INSERT_SUCCESS = 'SPK/SHIPPINGADV_EXP_INSERT_SUCCESS';
export const SHIPPINGADV_EXP_INSERT_FAIL = 'SPK/SHIPPINGADV_EXP_INSERT_FAIL';

export const SHIPPINGADV_EXP_FETCH_START = 'SPK/SHIPPINGADV_EXP_FETCH_START';
export const SHIPPINGADV_EXP_FETCH_SUCCESS = 'SPK/SHIPPINGADV_EXP_FETCH_SUCCESS';
export const SHIPPINGADV_EXP_FETCH_FAIL = 'SPK/SHIPPINGADV_EXP_FETCH_FAIL';

export const SHIPPINGADV_EXP_UPDATE_START = 'SPK/SHIPPINGADV_EXP_UPDATE_START';
export const SHIPPINGADV_EXP_UPDATE_SUCCESS = 'SPK/SHIPPINGADV_EXP_UPDATE_SUCCESS';
export const SHIPPINGADV_EXP_UPDATE_FAIL = 'SPK/SHIPPINGADV_EXP_UPDATE_FAIL';

export const SHIPPINGADV_EXP_DELETE_START = 'SPK/SHIPPINGADV_EXP_DELETE_START';
export const SHIPPINGADV_EXP_DELETE_SUCCESS = 'SPK/SHIPPINGADV_EXP_DELETE_SUCCESS';
export const SHIPPINGADV_EXP_DELETE_FAIL = 'SPK/SHIPPINGADV_EXP_DELETE_FAIL';

export const USER_UPDATE_START = 'SPK/USER_UPDATE_START';
export const USER_UPDATE_SUCCESS = 'SPK/USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'SPK/USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'SPK/USER_UPDATE_RESET';

export const USER_SELECT_START = 'SPK/USER_SELECT_START';
export const USER_SELECT_SUCCESS = 'SPK/USER_SELECT_SUCCESS';
export const USER_SELECT_FAIL = 'SPK/USER_SELECT_FAIL';

export const USER_RESET_PASSWORD_START = 'SPK/USER_RESET_PASSWORD_START';
export const USER_RESET_PASSWORD_SUCCESS = 'SPK/USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_FAIL = 'SPK/USER_RESET_PASSWORD_FAIL';
