export const SHIPPINGADV_EXP_INSERT_START = 'SPK/SHIPPINGADV_EXP_INSERT_START';
export const SHIPPINGADV_EXP_INSERT_SUCCESS = 'SPK/SHIPPINGADV_EXP_INSERT_SUCCESS';
export const SHIPPINGADV_EXP_INSERT_FAIL = 'SPK/SHIPPINGADV_EXP_INSERT_FAIL';

export const SHIPPINGADV_EXP_FETCH_START = 'SPK/SHIPPINGADV_EXP_FETCH_START';
export const SHIPPINGADV_EXP_FETCH_SUCCESS = 'SPK/SHIPPINGADV_EXP_FETCH_SUCCESS';
export const SHIPPINGADV_EXP_FETCH_FAIL = 'SPK/SHIPPINGADV_EXP_FETCH_FAIL';

export const SHIPPINGADV_EXP_UPDATE_START = 'SPK/SHIPPINGADV_EXP_UPDATE_START';
export const SHIPPINGADV_EXP_UPDATE_SUCCESS = 'SPK/SHIPPINGADV_EXP_UPDATE_SUCCESS';
export const SHIPPINGADV_EXP_UPDATE_FAIL = 'SPK/SHIPPINGADV_EXP_UPDATE_FAIL';

export const SHIPPINGADV_EXP_DELETE_START = 'SPK/SHIPPINGADV_EXP_DELETE_START';
export const SHIPPINGADV_EXP_DELETE_SUCCESS = 'SPK/SHIPPINGADV_EXP_DELETE_SUCCESS';
export const SHIPPINGADV_EXP_DELETE_FAIL = 'SPK/SHIPPINGADV_EXP_DELETE_FAIL';